// react-crud-users/src/Components/User/Details/DetailsComponent.js
import React from 'react';
import UserService from '../../../services/userService';
import { Link } from "react-router-dom";

class DetailsComponent extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      id: 0,
      name: '',
      email: ''
    };
  }

  componentDidMount() {
    if (this.props.match.params) {
      UserService.getUser(this.props.match.params.id).then(response => {
        if (response.status = 200) {
          const { id, name, email } = response.data
          this.setState({ id, name, email })
        } else {
          alert('Erro ' + response.status)
        }        
      }).catch(error => {
        alert(error)
      })
    }
  }

  render() {
    return (
      <div>
        <h2>Detalhes usuário</h2>

        <hr />
        <div>
          <div>
            <label><b>Nome: </b></label> {this.state.name === null ? '' : this.state.name}
          </div>
          <div>
            <label><b>Email: </b></label> {this.state.email === null ? '' : this.state.email}
          </div>
        </div>

        <br />
        <br />
        <Link to='/users' class="btn btn-primary">Voltar para lista usuários</Link>
        <br />        
      </div>
    );
  }
}

export default DetailsComponent;

// angular-crud-users/src/app/components/user/details/details.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { User } from '../../../models/user/user';
import { UserService } from '../../../services/user/user.service';
import { Router, ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.css']
})
export class DetailsComponent implements OnInit {

  id: number;
  user: User;

  constructor(private route: ActivatedRoute, private router: Router,
    private UserService: UserService) { }

  ngOnInit() {
    this.user = new User();

    this.id = this.route.snapshot.params['id'];

    this.UserService.getUser(this.id)
      .subscribe(data => {
        console.log(data)
        this.user = data;
      }, error => console.log(error));
  }

  list() {
    this.router.navigate(['users']);
  }
}

<h2>Detalhes usuário</h2>

<hr />
<div *ngIf="user">
    <div>
        <label><b>Nome: </b></label> {{user.name}}
    </div>
    <div>
        <label><b>Email: </b></label> {{user.email}}
    </div>
</div>

<br>
<br>
<button (click)="list()" class="btn btn-primary">Voltar para lista usuários</button><br>
